services:
  postgres:
    ports: []
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    ports: []
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  minio:
    ports: []
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  meilisearch:
    ports: []
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  worker:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G

  frontend:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

